services:
  # ===========================================
  # FRONTEND SERVICE (React)
  # ===========================================
  frontend:
    build:
      context: ./ui_task_manager
      dockerfile: Dockerfile
    container_name: task_manager_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # ===========================================
  # BACKEND SERVICE (Go)
  # ===========================================
  backend:
    build:
      context: ./task-manager-server
      dockerfile: Dockerfile
    container_name: task_manager_backend
    ports:
      - "8080:8080"
    environment:
      - PUBLIC_HOST=http://localhost
      - PORT=8080
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=sibhelly1837
      - DB_NAME=plane_task_db
      - JWT_SECRET=your-secret-key-here
      - JWT_EXP=604800
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  # ===========================================
  # DATABASE SERVICE (MySQL)
  # ===========================================
  database:
    image: mysql:8.0
    container_name: task_manager_database
    environment:
      - MYSQL_ROOT_PASSWORD=sibhelly1837
      - MYSQL_DATABASE=plane_task_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-psibhelly1837",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
